"""resize embedding vector to 3456

Revision ID: 95e7a518e4b7
Revises: 893b0a471411
Create Date: 2025-07-18 09:55:45.710669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector  # type: ignore[import-not-found]


# revision identifiers, used by Alembic.
revision: str = '95e7a518e4b7'
down_revision: Union[str, Sequence[str], None] = '893b0a471411'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_samples',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('embedding', Vector(dim=3456), nullable=False),
    sa.Column('label', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('predictions', 'embedding',
               existing_type=Vector(dim=384),
               type_=Vector(dim=3456),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('predictions', 'embedding',
               existing_type=Vector(dim=3456),
               type_=Vector(dim=384),
               existing_nullable=False)
    op.drop_table('training_samples')
    # ### end Alembic commands ###
