services:
  postgres:
    image: pgvector/pgvector:0.6.0-pg16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-risk}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-risk}
      POSTGRES_DB: ${POSTGRES_DB:-risk}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "risk"]
      interval: 10s
      retries: 5

  api:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: risk
      DATABASE_URL: postgresql+asyncpg://risk:risk@postgres:5432/risk
    ports:
      - "8000:8000"

volumes:
  pgdata: 